### ISSUE TITLE
Sadness Author 

### ISSUE THREAD

**Issue by js-sadness** [js-sadness/js-sadness.github.io#38]
Should we add an author tag for the sadnesses? 

```yml
---
layout: sadness
title: " "
author: 
  name: " "
  # links optional
  website: " " 
  github: " " 
  ...
---
```
